server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default

logging.config: "classpath:logback.xml"

management:
  endpoints.web:
    base-path: /internal
    exposure.include: health

aiven-kafka:
  auto-offset-reset: none
  security-protocol: SSL
